data tilley;
   length loc $8.;
   infile "tilley.csv" dsd firstobs=2;
   input density loc $ yield;
   y=log(yield);
run;
proc glm data=tilley;
   class loc density;
   model y=density|loc;
   lsmeans density*loc/slice=loc;
   estimate "linear density,Lewis" density -3 -1 1 3 density*loc -3 -1 1 3;
   estimate "linear density,Plymouth" density -3 -1 1 3 density*loc 0 0 0 0   -3 -1 1 3;
   estimate "Pslope-Lslope" density*loc 3 1 -1 -3 -3 -1 1 3;
   contrast "linear density,Lewis" density -3 -1 1 3 density*loc -3 -1 1 3;
   contrast "linear density,Plymouth" density -3 -1 1 3 density*loc 0 0 0 0   -3 -1 1 3;
   output out=rez r=rez p=yhat;
run;
symbol value=dot;
proc gplot data=rez;
   plot rez*yhat=loc;
   plot rez*yhat=density;
run;