options ls=105 nocenter ps=1000 nodate;
data one;
   length model $20;
   infile "/home/u49844961/sasuser.v94/ST518/Homework 4/mtcars.csv" firstobs=2 dsd;
  input model $ mpg  cyl  disp  hp  drat  wt  qsec  vs  am  gear  carb; 
  disp2=disp**2;  gear2=gear**2; hp2=hp**2;
run;
symbol value=dot;
*goptions dev=pdf;
ods graphics on;
ods trace on;
proc reg data=one;
   model  mpg=cyl disp hp drat wt qsec vs am gear carb /selection=cp aic mse;
   model  mpg=wt qsec am disp disp2;
   output out=residz r=r p=p;
   ods output SubsetSelSummary = BigTable;
run;
proc corr data = one;
with mpg;
run;
proc sgscatter data = one;
matrix mpg cyl  disp  hp  drat  wt  qsec  vs  am  gear  carb;
run;
proc sort data = BigTable;
 by cp;
run;
 proc print data = BigTable (obs = 10) nolabel;
run;
/*
proc gplot data=residz;
   title "residuals vs fitted(i)";
   title2 "observed vs fitted(iii)";
   plot r*p;
   plot mpg*p;
run;*/
proc sort data=residz;
   by r;
run;
data residz;
   set residz;
   qnorm=quantile("norm",_n_/33);
run;
proc print data = residz;run;
proc gplot data = residz;
   title "qqnormal plot(ii)";
   plot qnorm*r;
run;
